# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

app_identifier "dev.zhangyu.volume-hud"

api_key_path ENV["APP_STORE_CONNECT_API_KEY_JSON_PATH"]

platform "osx"
app_version "1.0.5"

force true

skip_screenshots true
skip_binary_upload true
submit_for_review false
automatic_release false
run_precheck_before_submit false